language: ruby
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
script: bundle exec fastlane ci_test
notifications:
  email:
    on_success: never
    on_failure: change
